kakeibo/urls.py
from django.urls import path

from . import views

app_name = 'kakeibo'

urlpatterns = [
    path('kakeibo_list/', views.KakeiboListView.as_view(), name='kakeibo_list'),
    path('kakeibo_create/',views.KakeiboCreateView.as_view(),name = 'kakeibo_create'),
    path('create_done/', views.create_done, name='create_done'),
    path('update/<int:pk>/', views.KakeiboUpdateView.as_view(), name='kakeibo_update'),
    path('update_done/', views.update_done, name='update_done'),
    path('delete/<int:pk>/', views.KakeiboDeleteView.as_view(), name='kakeibo_delete'),
    path('delete_done/', views.delete_done, name='delete_done'),
    path('circle/',views.show_circle_graph, name='kakeibo_circle'),
    path('line/', views.show_line_graph,name='kakeibo_line'),
    ]

tutorial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include   #追加

urlpatterns = [
   path('admin/', admin.site.urls),
   path('kakeibo/', include('kakeibo.urls')),   #追加
]

kakeibo/models.py
from django.db import models
from datetime import datetime


class Category(models.Model):
    class Meta:
        # テーブル名
        db_table = "category"
        verbose_name = "カテゴリ"
        verbose_name_plural = "カテゴリ"

    # カラム名の定義
    category_name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.category_name


class Kakeibo(models.Model):
    class Meta:
        # テーブル名
        db_table = "kakeibo"
        verbose_name = "家計簿"
        verbose_name_plural = "家計簿"

    # カラムの定義
    date = models.DateField(verbose_name="日付", default=datetime.now)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name="カテゴリ")
    money = models.IntegerField(verbose_name="金額", help_text="単位は日本円")
    memo = models.CharField(verbose_name="メモ", max_length=500,help_text="必須項目です。")

    def __str__(self):
        return self.memo
# Create your models here.

kakeibo/forms.py
from django import forms
from .models import Kakeibo

class KakeiboForm(forms.ModelForm):
    # 新規データの登録画面
    class Meta:
        model = Kakeibo
        fields = ["date","category","money","memo"]

kakeibo/views.py
from django.shortcuts import render
from . forms import KakeiboForm
from django.urls import reverse_lazy
# Create your views here.
#ここから下を追加
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .models import Category, Kakeibo
from django.db import models
from django.db.models import Sum
import calendar

#一覧表示用のDjango標準ビュー(ListView)を承継して一覧表示用のクラスを定義
class KakeiboListView(ListView):
   #利用するモデルを指定
   model = Kakeibo
   # データを渡すテンプレートファイルを指定
   template_name = 'kakeibo/kakeibo_list.html'

   #家計簿テーブルの全データを取得するメソッドを定義
   def queryset(self):
       return Kakeibo.objects.all()

class KakeiboCreateView(CreateView):
    model = Kakeibo
    form_class = KakeiboForm
    success_url =  reverse_lazy('kakeibo:create_done')

def create_done(request):
    return render(request,'kakeibo/create_done.html')

class KakeiboUpdateView(UpdateView):
    model = Kakeibo
    form_class = KakeiboForm
    success_url = reverse_lazy('kakeibo:update_done')

def update_done(request):
    return render(request,'kakeibo/update_done.html')

class KakeiboDeleteView(DeleteView):
    model = Kakeibo
    success_url = reverse_lazy('kakeibo:delete_done')

def delete_done(request):
    return render(request,'kakeibo/delete_done.html')


def show_circle_graph(request):
    # 全データ取得
    kakeibo_data = Kakeibo.objects.all()

    # すべての金額の合計を求める
    total = 0
    for item in kakeibo_data:
        total += item.money

    category_list = []
    # 全カテゴリ名をテーブルから取得する。
    category_data = Category.objects.all()
    # ループ処理でカテゴリ名のリストを作成する。
    for item in category_data:
        category_list.append(item.category_name)
    # つづいてカテゴリ毎の合計金額を求める
    category_dict = {}
    for i, item in enumerate(category_list):
        category_total = Kakeibo.objects.filter(category__category_name=category_list[i]).aggregate(sum=models.Sum('money'))['sum']
        # 割合を計算する
        if category_total != None:
            ratio = int((category_total / total) * 100)
            category_dict[item] = ratio
        else:
            ratio = 0
            category_dict[item] = ratio

    return render(request, 'kakeibo/kakeibo_circle.html', {
        'category_dict': category_dict,
    })
# 月々のカテゴリ別の使用金額を折れ線グラフで表示
def show_line_graph(request):

    kakeibo_data=Kakeibo.objects.all()

    #カテゴリリストデータの生成
    category_list=[]
    category_data =Category.objects.all().order_by('-category_name')
    for item in category_data:
        category_list.append(item.category_name)
    date_list=[]
    for i in kakeibo_data:
        date_list.append((i.date.strftime('%Y/%m/%d')[:7]))
        date_list.sort()
    #重複値の除外
    x_label = list(set(date_list))
    x_label.sort(reverse=False)

    #月毎&カテゴリー毎の合計金額データセット
    monthly_sum_data=[]
    for i in range(len(x_label)):
        year,month = x_label[i].split("/")
        month_range = calendar.monthrange(int(year),int(month))[1]
        first_date = year + '-'+month + '-'+'01'
        last_date =year +'-'+month+'-'+str(month_range)
        #１ヶ月分のデータ
        total_of_month =Kakeibo.objects.filter(date__range=(first_date,last_date))
        category_total = total_of_month.values('category').annotate(total_price=Sum('money'))
    for j in range(len(category_total)):
        money =category_total[j]['total_price']
        category =Category.objects.get(pk=category_total[i]['category'])
        monthly_sum_data.append([x_label[i],category.category_name,money])

    #折れ線グラフのボーダーカラー
    border_color_list = ['254,97,132,0.8', '54,164,235,0.8', '0,255,65,0.8', '255,241,15,0.8',
                        '255,94,25,0.8', '84,77,203,0.8', '204,153,50,0.8', '214,216,165,0.8',
                        '33,30,45,0.8', '52,38,89,0.8']
    border_color =[]
    for x,y in zip(category_list, border_color_list):
        border_color.append([x,y])

    background_color_list = ['254,97,132,0.5', '54,164,235,0.5', '0,255,65,0.5', '255,241,15,0.5',
                            '255,94,25,0.5', '84,77,203,0.5', '204,153,50,0.5', '214,216,165,0.5'
                            '33,30,45,0.5', '52,38,89,0.5']
    background_color=[]
    for x,y in zip(category_list,background_color_list):
        background_color.append([x,y])

    matrix_list=[]
    for item_label in x_label:
        for item_category in category_list:
            matrix_list.append([item_label,item_category,0])
    """ matrix_listとmonthlysum_dataに対して、「年月+カテゴリ」の
        組み合わせが一致する要素に対してmatrix_listの金額（０円）を
        monthly_sum_dataの金額で上書きする。
    """
    for yyyy_mm,category,total in monthly_sum_data:
            for i,data in enumerate(matrix_list):
                if data[0]==yyyy_mm and data[1] ==category:
                    matrix_list[i][2] = total
    return render(request,'kakeibo/kakeibo_line.html',{
        'x_label':x_label,
        'category_list':category_list,
        'border_color':border_color,
        'background_color':background_color,
        'matrix_list':matrix_list,
    })

kakeibo/templates/kakeibo/base.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {# Bootstrap4を使う #}
  <!-- linkタグでbootstrapのcssファイルを読み込む -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
  <!-- linkタグでDataTableのcssファイルを読み込む -->
  <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css"/>

  <!-- タイトルの設定-->
  <title>Tutorial</title>

<body>

  {% block content %}

   <!-- block content ～ endblockの間に子テンプレートの内容が差し込まれる -->

  {% endblock %}

  <!-- bootstrapのjavascrit読み込み-->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
  <!-- DataTablesのjavascrit読み込み-->
  <script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>
  <!-- chart.jsの読み込み -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>

  <!-- Databableの定義-->
  <script>
  jQuery(function($){
    // デフォルトの設定を変更
    $.extend( $.fn.dataTable.defaults, {
        language: {
            url: "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
            }
            });
    $("#kakeibo_list").DataTable({
        "searching": true,     //検索機能
        "paging":   true,      //ページング機能
        "ordering": true,      //ソート機能
        "lengthChange": true,  //件数切り替え機能

        }).columns.adjust().draw();
        });
  </script>

  <!-- 描画する円グラフの定義-->
  <script>
    var ctx = document.getElementById('CircleChart').getContext('2d');
    var data = [
                [
                 {% for key, value in category_dict.items%}
                  '{{key}}',
                 {% endfor %}
                ],

                [
                {% for key, value in category_dict.items%}
                   {{value}},
                {% endfor %}
                ]]

    var myChart = new Chart(ctx, {
      type: 'pie',

      data: {
        labels: data[0],
        datasets: [{
          data:  data[1],
          backgroundColor: ["rgba(255,241,15,0.8)","rgba(54,164,235,0.8)",
          "rgba(0,255,65,0.8)","rgba(214,216,165,0.8)","rgba(255,94,25,0.8)",
          "rgba(84,77,203,0.8)","rgba(140,140,140,0.8)","rgba(171,255,127,0.8)",
          "rgba(50,204,18,0.8)","rgba(234,210,173,0.8)"],
        },
      ] }
    });
</script>
<!-- 折れ線グラフの設定-->
<script>
  var ctx = document.getElementById("LineChart").getContext('2d');
  var DiskChart = new Chart(ctx, {
  type: 'line',
    data: {
      labels:[
          {% for item in x_label %}
            "{{ item }}",
          {% endfor %}],
      datasets: [
          {% for category_name in category_list %}
              {
                label: "{{ category_name }}",
                fill: false,
              {% for category ,color in border_color %}
                  {% if category == category_name %}
                    borderColor: 'rgba({{ color }})',
                  {% endif %}
              {% endfor %}
              {% for category ,color in background_color %}
                  {% if category == category_name %}
                    backgroundColor: 'rgba({{ color }})',
                  {% endif %}
              {% endfor %}

                data: [
                    {% for time_label in x_label %}

                      {% for date, category, total in matrix_list %}
                         {% if category == category_name %}
                            {% if date == time_label %}
                              {{total}},
                            {% endif %}
                         {% endif %}
                      {% endfor %}
                        {% endfor %}
                ],
              },
          {% endfor %}
      //以下を追加

    ]
  },
  options: {
       responsive: true,
       scales: {
         xAxes: [{
           scaleLabel: {
             display: true,
             labelString: '時間'
           },
           ticks: {                      // 目盛り
               maxRotation:0, //X軸の表示角度調整
               minRotation:0  //X軸の表示角度調整
             },
           }],
           yAxes: [{
             scaleLabel: {
               display: true,
               labelString: '合計金額（円）'
             },
           ticks:{
             min: 0,   // 最小値
             }
            }],
          },
         title: {
           display: true,         // 表示設定
           pocision: "top",       // 表示位置
           fontSize: 30,          // フォントサイズ
           fontColor: "black",    // 文字の色
           text: "月毎の合計金額推移" // タイトル文字列
         },
    }
});
</script>
</body>
</html>

kakeibo/templates/kakeibo/create_done.html
{% extends 'kakeibo/base.html' %}
{% block content %}

 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'kakeibo:kakeibo_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">家計簿アプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <i class="fa fa-server"></i> <b>家計簿アプリ</b></div>
       <div class="card-body">
<div class="alert alert-info" role="alert">データ登録が正常終了しました。</div>
{% endblock content %}

kakeibo/templates/kakeibo/delete_done.html
{% extends 'kakeibo/base.html' %}
{% block content %}

 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'kakeibo:kakeibo_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">家計簿アプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <i class="fa fa-server"></i> <b>家計簿アプリ</b></div>
       <div class="card-body">
         <div class="alert alert-info" role="alert">データ削除処理が正常終了しました。</div>
{% endblock content %}

kakeibo/templates/kakeibo/kakeibo_circle.html
{% extends 'kakeibo/base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- パンくずリストの設定-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'kakeibo:kakeibo_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">カテゴリ毎の合計金額割合</li>
     </ol>
     <!--ページタイトル-->
     <div class="card mb-3">
       <div class="card-header">
          <h3><b>家計簿アプリ（カテゴリ毎の合計金額割合）</b></h3></div>
       <div class="card-body">
         <!-- 円グラフの描画-->
         <div class="chart_container">
             <canvas id='CircleChart' style="position: relative; height:1vh; width:1vw"></canvas>
           </div>
       </div>
      </div>
   </div>
  </div>
   <style>
      .chart_container {
          width: 640px;
          margin: auto;
        }
  </style>
{% endblock content %}

kakeibo/templates/kakeibo/kakeibo_confirm_delete.html
{% extends 'kakeibo/base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'kakeibo:kakeibo_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">家計簿アプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <h3>データ削除</h3></div>
       </div>
       <div class="content-wrapper">
         <div class="container-fluid">
           <p>{{ object }} のデータを削除していいですか?</p>
<!--           更新処理だからPOST-->
           <form method="post">
             <button class="btn btn-danger">削除する</button>
<!--               CSRF対策-->
             {% csrf_token %}
           </form>
         </div>
       </div>
   </div>
 </div>
{% endblock %}

kakeibo/templates/kakeibo/kakeibo_form.html
{% extends 'kakeibo/base.html' %}
{% load bootstrap %}
{% block content %}
 <form method="post">
   <div class="container">
     <div class="row">
       <div class="col-12">
         <div class="content-wrapper">
           <div class="container-fluid">
             <!-- Breadcrumbs-->
             <ol class="breadcrumb">
               <li class="breadcrumb-item">
                 <a href="{% url 'kakeibo:kakeibo_list' %}">TOP</a>
               </li>
               <li class="breadcrumb-item active">家計簿アプリ</li>
               <li class="breadcrumb-item active">データ登録</li>
             </ol>
             <!-- Example DataTables Card-->
             <div class="card mb-3">
               <div class="card-header">
                 <i class="fa fa-server"></i> <h3>データ登録画面</h3></div>
               <div class="card-body">          {{ form|bootstrap }}

       </div>
     </div>
     <div class="row">
       <div class="col-12">
         <button class="btn btn-primary">保存</button>
       </div>
     </div>
   </div>
   {% csrf_token %}
 </form>
{% endblock %}

kakeibo/templates/kakeibo/kakeibo_line.html
<!-- 親テンプレートを読み込む-->
{% extends './base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- パンくずリストの設定-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'kakeibo:kakeibo_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">カテゴリ毎の合計金額推移</li>
     </ol>
     <!--ページタイトル-->
     <div class="card mb-3">
       <div class="card-header">
          <h3><b>家計簿アプリ（カテゴリ毎の合計金額推移）</b></h3></div>
       <div class="card-body">

         <!-- 円グラフの描画-->
         <div class="chart_container">
             <canvas id='LineChart' style="position: relative; height:25vh; width:25vw"></canvas>
         </div>
         <table id=kakeibo_list width="100%" class="table table-striped table-hover">
             <thead>
                <tr style="background-color: aquamarine">
                    <th class="text-center width=10">日付</th>
                    <th class="text-center">カテゴリ</th>
                    <th class="text-center">合計金額</th>
                </tr>
             </thead>
             <hr>
             <tbody>
                {% for date,category, total in matrix_list %}
                    <tr class="odd gradeX text-center">
                        <td class="text-center">{{ date }}</td>
                        <td class="text-center">{{ category }}</td>
                        <td class="text-center">{{ total }}</td>
                    </tr>
                {% endfor %}
             </tbody>
         </table>

       </div>
      </div>
   </div>
  </div>
    <style>
    @media screen and (min-width: 768px){
        .chart_container{
            width: 640px;
            margin: auto;
        }
    }
    </style>
{% endblock content %}

kakeibo/templates/kakeibo/kakeibo_list.html
{% extends 'kakeibo/base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- パンくずリストの設定-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'kakeibo:kakeibo_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">一覧表示</li>
       <li class="breadcrumb-item">
         <a href="{% url 'kakeibo:kakeibo_create' %}">新規作成</a>
       </li>
       <li class="breadcrumb-item">
           <a href="{% url 'kakeibo:kakeibo_circle' %}">円グラフ</a>
       </li>
         <li class="breadcrumb-item">
           <a href="{% url 'kakeibo:kakeibo_line' %}">月毎の合計金額推移</a>
       </li>

     </ol>
     <!--ページタイトル-->
     <div class="card mb-3">
       <div class="card-header">
         <h3><b>家計簿アプリ</b></h3></div>
       <div class="card-body">
         <!-- テーブル表の定義 -->
         <div class="table-responsive">
         <table id=kakeibo_list width="100%" class="table table-striped table-bordered table-hover">
           　<!-- 表の列の定義-->
             <thead>
               <tr>
                 <th class="text-center">日付</th>
                 <th class="text-center">カテゴリ</th>
                 <th class="text-center">金額</th>
                 <th class="text-center">メモ</th>
                 <th class="text-center">更新・削除</th>
               </tr>
             </thead>
           　<!-- ここまでが表の列の定義-->
           　<!-- 表のデータ部分の表示-->
             <tbody>
               {% for item in object_list %}
                 <tr class="odd gradeX text-center">
                   <td class="text-center" width="100">{{ item.date}}</td>
                   <td class="text-center" width="100">{{ item.category }}</td>
                   <td class="text-center" width="140">{{ item.money }}</td>
                   <td class="text-center" width="140">{{ item.memo }}</td>
                   <td class="text-center" width="140">
                     <a class="btn btn-primary" href="{% url 'kakeibo:kakeibo_update' item.pk %}" >
                     更新ページ</a>
                     <a class="btn btn-danger" href="{% url 'kakeibo:kakeibo_delete' item.pk %}">削除ページ</a>
                   </td>

                 </tr>
             {% endfor %}
             </tbody>
           　<!-- ここまでが表のデータ部分の表示-->
           </table>
           <!-- ここまでがテーブル表の定義 -->
       </div>
      </div>
      </div>
   </div>
  </div>
{% endblock content %}

kakeibo/templates/kakeibo/update_done.html
{% extends 'kakeibo/base.html' %}
{% block content %}

 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'kakeibo:kakeibo_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">家計簿アプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <i class="fa fa-server"></i> <b>家計簿アプリ</b></div>
       <div class="card-body">
<div class="alert alert-info" role="alert">データの更新処理が正常終了しました。</div>
{% endblock content %}